### ISSUE TITLE
json representation doesnt work

### ISSUE THREAD

**Issue by suman291857** [martypitt/swagger-springmvc-example#15]
Hi,
Iam trying to get this example working for json
Here are the URLs.XML works fine but json is broken
It seems like 
 return apiReader.getDocumentation(fullUrl.substring(indexOfApiName));
returns api name with .json to the end and framework fails to recognise the resource
Here are the URLs iam trying to use

Json doesnt work but XML works
http://localhost:8080/swagger-springmvc-test/api-docs/pets.json
http://localhost:8080/swagger-springmvc-test/api-docs/pets

Both Of them works:
http://localhost:8080/swagger-springmvc-test/api-docs
http://localhost:8080/swagger-springmvc-test/api-docs.json

**Comment by dilipkrish** [comment]
@suman291857 The file extension is not really supported. You'd need to send in the right accept header. Either application/json or application/xml

**Comment by xiemeilong** [comment]
@dilipkrish  the request is send by swagger-ui , how can I change the accept header?

**Comment by billybong** [comment]
Is there any way to alter the default so that it is json rather than xml? I'd love to use this plugin, but as both Swagger-UI and the SOAP-UI Swagger plugin does not send an accept header it is not usable for me without the ability to change this server side. Changing the default to json would also make more sense in a REST context.

**Comment by dilipkrish** [comment]
@billybong ultimately it all goes through jquery and ajax requests. So [a simple default header](http://stackoverflow.com/questions/12347211/pass-accepts-header-parameter-to-jquery-ajax) should do the trick in the swagger-ui application.

**Comment by billybong** [comment]
Yes I know, but some other tools such as i.e. the SoapUI swagger plugin does not send the accept header. So you have to jump through hoops to get the result you want. Therefore I'd simply think it makes more sense to default to JSON as that is the de-facto rest "standard" format. I agree that in a perfect world everyone should clearly state the required format, but since that's not the case why not adapt to what almost every other type of application expects? That being said I think this plugin is awesome and I'm already using it for our latest project.

**Comment by dilipkrish** [comment]
@billybong  In that case I would just remove the jaxb libraries from the dependencies or exclude them. Or if you're setting up your message converters manually, exlude the message converters for application/xml
